name: Build and Deploy 

on:
  push:
    branches: ['main'] 

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: TartanLlama/actions-eleventy@master

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
